
"""
This code is developed for sending automated whatsapp messages.
This is intended to be used for Rotaract Purposes only.

Developers:
1. Rtn. PP. Rtr. Akshay Kumar Kanive M
2. Rtn. Rtr. Bhuvan M R

In case of any queries, please write to akshaykanive@gmail.com or bhuvanmr575@gmail.com
"""

#Import required modules
import time
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.ui import WebDriverWait
from webdriver_manager.chrome import ChromeDriverManager

BASE_URL = "https://web.whatsapp.com/"
CHAT_URL = "https://web.whatsapp.com/send?phone={phone}&text&type=phone_number&app_absent=1"


chrome_options = Options()
chrome_options.add_argument("start-maximized")
#Set the path based on OS. Sample settings has been done for MacBook Pro M1
user_data_dir = "/Users/akshaykanive/Library/Application Support/Google/Chrome/Default"
chrome_options.add_argument("--user-data-dir=" + user_data_dir)

#Uncomment to use incognito window
#chrome_options.add_argument("--incognito")

#Start a chrome webdriver instance
browser = webdriver.Chrome(ChromeDriverManager().install(),  options=chrome_options,)

browser.get(BASE_URL)
browser.maximize_window()


#Sample Data
phone = ["919742271407","919611261259"]
messagel1 = """Hi There. This is test message from 3190 Tech Team."""
messagel2 = "Your ticket is here: www.google.com"
messagel3 = "This is autogenerated message. Kindly do not reply to this message"

#Refer to https://gist.github.com/hkan/264423ab0ee720efb55e05a0f5f90887 for emojis info
messagel4 = "Testing Fire Emoji :fire\n"


for i in range(len(phone)):
    browser.get(CHAT_URL.format(phone=phone[i]))
    time.sleep(5)


    inp_xpath = (
        '//*[@id="main"]/footer/div[1]/div/span[2]/div/div[2]/div[1]/div/div[1]'
    )
    input_box = WebDriverWait(browser, 60).until(
        expected_conditions.presence_of_element_located((By.XPATH, inp_xpath))
    )
    input_box.send_keys(messagel1)
    #Use shift+enter conbination for going to next line without sending the message. Else each line will be sent as one message.
    input_box.send_keys(Keys.SHIFT + Keys.ENTER)
    input_box.send_keys(messagel2)
    input_box.send_keys(Keys.SHIFT + Keys.ENTER)
    input_box.send_keys(messagel3)
    input_box.send_keys(Keys.ENTER)
    #Time interval to deliver the message
    time.sleep(10)